### ISSUE TITLE
Two instances of Program Manager II can be ran at the same time

### ISSUE THREAD

**Issue by freedom7341** [Vortesys/Program-Manager-II#11]
Shouldn't be possible. Opening a new instance should attempt to find another open copy and redirect focus to it.

**Comment by TheColorOfFear** [comment]
possibly conflicts with #25 ?

**Comment by freedom7341** [comment]
> this goal possibly conflicts with #25 ?

not really, in the original progman if you opened a new instance of program manager from within itself it would simply kill the new instance and keep the old one but rename the titlebar
