### ISSUE TITLE
System Error on Windows 7

### ISSUE THREAD

**Issue by TheColorOfFear** [Vortesys/Program-Manager-II#34]
starting in ef888042 , trying to run progmgr on windows 7 shows this system error. a494e057 and prior run flawlessly
![image](https://github.com/Vortesys/Program-Manager-II/assets/68704661/b1ced6c4-3bfe-4584-a9b4-e2e61bc5d1e5)

**Comment by TheColorOfFear** [comment]
wasn't fixed in 06e32d9, still an issue as of bbf9941

**Comment by freedom7341** [comment]
should be fixed in vista compatibilty commits
